{% set version = "0.0.7" %}
{% set sha256 = "baacca27f9b34239d3ab4725d83b556d7639fd0ef0a47adddbbadaa339213410" %}

package:
  name: kcollections
  version: '{{version}}'

source:
  url: https://github.com/masakistan/kcollections/archive/{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  number: 0

requirements:
  build:
    - llvm

test:
  commands:
    - python -c 'from kcollections import Kdict, Kset'

about:
  home: https://github.com/masakistan/kcollections
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A Bloom Filter Trie implementation with Python bindings that allows
    memory efficient kmer storage and lookup. Replaces the default Python set and
    dict for use with kmers.
